version: '2'

volumes:
  eticket_main_data:
    external: true

networks:
  eticket_net:
    driver: bridge

services:
  eticket_mysql:
    image: 'mysql:8.1'
    container_name: eticket_mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: eticket
      MYSQL_ROOT_PASSWORD: hello_eticket
      TZ: Asia/Seoul
    volumes:
    - eticket_main_data:/var/lib/mysql
    networks:
    - eticket_net

  eticket_backend:
    build: ./Dockerfile/
    container_name: eticket_backend
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://eticket_mysql:3306/eticket
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: hello_eticket
    ports:
    - 8080:8080
    networks:
    - eticket_net
