version: "2"

networks:
  eticket_net:
    external: true

services:
  eticket_backend:
    env_file:
      - ../env/eticket-dev-datasource.env
    environment:
      ETICKET.REDIS.AUTH.HOST: eticket_redis
      ETICKET.REDIS.AUTH.PORT: 6379
      ETICKET.REDIS.AUTH.DATABASE: 1
    build: ../../workspace/backend/Dockerfile/
    container_name: eticket_backend
    image: eticket/backend
    restart: on-failure
    ports:
      - 38080:8080
    networks:
      - eticket_net
