version: "2"

services:
  eticket_ipfs_uploader:
    build: ../../workspace/blockchain-ipfs-uploader/Dockerfile
    image: eticket/ipfs-uploader
    container_name: eticket-ipfs_uploader
    restart: on-failure
    environment:
      ETICKET_KUBO_RPC_URL: http://localhost:60882
    ports:
      - 35001:35001
    network_mode: host
