version: "2"

volumes:
  eticket_main_data:
    external: true

networks:
  eticket_net:
    driver: bridge

services:
  eticket_mysql:
    image: "mysql:8.1"
    container_name: eticket_mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: hello_eticket
      TZ: Asia/Seoul
    volumes:
      - "eticket_main_data:/var/lib/mysql"
      - "./services/mysql/initdb.d:/docker-entrypoint-initdb.d"
    expose:
      - 33066
    networks:
      - eticket_net

  eticket_redis:
    image: "redis:7.2"
    container_name: eticket_redis
    restart: on-failure
    networks:
      - eticket_net

  eticket_blockchain_tracker:
    build: ../blockchain-tracker/Dockerfile/
    container_name: eticket_blockchain_tracker
    restart: on-failure
    environment:
      ETICKET_BLOCKCHAIN_RPC_URL: https://j9c203.p.ssafy.io/services/blockchain/rpc
      ETICKET_BLOCKCHAIN_CONTRACT_ADDRESS: "0xC80aC17c73AcC311ececb2A75eC3170D6C73fEa6"
      ETICKET_BLOCKCHAIN_LOWER_BLOCK: "-1"
      ETICKET_DATASOURCE_URL: "eticket_mysql:3306"
      ETICKET_DATASOURCE_USERNAME: root
      ETICKET_DATASOURCE_PASSWORD: hello_eticket
    networks:
      - eticket_net

  eticket_backend:
    build: ../backend/Dockerfile/
    container_name: eticket_backend
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://eticket_mysql:3306/eticket
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: hello_eticket
      ETICKET.REDIS.AUTH.HOST: eticket_redis
      ETICKET.REDIS.AUTH.PORT: 6379
      ETICKET.REDIS.AUTH.DATABASE: 1
    ports:
      - 8080:8080
    networks:
      - eticket_net
